---
- name: Get commitid
  shell: cd {{ input_dir }} && git rev-parse HEAD
  register: reg_commitid

- set_fact:
    project: 
      url: https://github.com/AnsibleCI/ansible-role-demo
      name: ansible-role-demo
      commitid: "{{ reg_commitid.stdout }}"
      
- name: Save ansible-lint results in '{{ output_results_file }}'
  shell: cd {{ input_dir }} && ansible-lint --parseable-json playbook_demo.yml > {{ output_results_file }}
  register: command
  failed_when: command.rc != 0 and command.rc != 2

- name: "Create '{{ output_project_commit_dir }}' directory" 
  file:
    path: "{{ output_project_commit_dir }}"
    state: directory

- name: Generate '{{ output_ansiblelint_file }}'
  template:
    src: page_ansible-lint.html.j2
    dest: "{{ output_ansiblelint_file }}"